### ISSUE TITLE
メジャーバージョンアップデート（超破壊的更新）のときのタスク一覧

### ISSUE THREAD

**Issue by Hiroshiba** [VOICEVOX/voicevox_project#18]
いつか破壊的更新をしたいということがいろいろあるのですが、一覧化しておかないと忘れそうなのでしておこうと思います。

- [ ] prePhonemeLengthなどをprePhonemeTimeに変える
- [ ] AudioQueryの引数のケースをどちらかに統一する
- [ ] engine_id・speaker_id・style_id周りの整理（voice_idにする？）
- [ ] 声を指定するときのパラメータどうするか（style_idのまま？voice_id？speaker_id+style_id？）
- [ ] styleidを整数からUUID文字列にする
- [ ] metasをリストからdictにする
- [ ] ロゴ変える
- [ ] releaseのパッケージ名を統一する（prefix, OS, arch, device, versionの順番）
- [x] electron-storeからの脱却（[完了](https://github.com/VOICEVOX/voicevox/issues/1156)）
- [ ] エディタの設定を１つの構造体にする
- [ ] engine_manifestのキーをパスだとわかるようにする
- [ ] `/engine_manifest`のレスポンスのsupported_featureをリッチにして`engine_manifest.json`と揃える [(issue)](https://github.com/VOICEVOX/voicevox_engine/issues/1550)
- [ ] デフォルトポートを変える
- [ ] エンジン・コア・runtime・ライブラリの役割分離を見直す
- [ ] audio_queryにspeakerを含める
- [ ] 「AquesTalkライクな記法」の別の呼び方考える→AquesTalk風記法？
- [ ] zipファイルの中身のディレクトリは汎用的な名前で統一する？（エンジンはバージョン名は無いがOS名などが入る、エディタは「VOICEVOX」、コアはOSやバージョン名が入る）
- [ ] 辞書API`GET /user_dict`の情報を`POST /user_dict_word`程度に減らす
- [ ] エンジンとblogのメインブランチをmainにする
- [ ] エンジンのpreset系のAPIとuser_dict_word系のAPIでdeleteやupdateのインターフェイスが異なる
- [ ] VOICEVOX API json フィールドの case を統一する（[ENGINE issue](https://github.com/VOICEVOX/voicevox_engine/issues/460)）
- [ ] エンジンのアイコン・立ち絵・サンプルボイスなどをバイナリのbase64文字列からURL等に変更する
- [ ] エンジンのデフォルトの出力文字コードをUTF8にする
- [ ] aarch64とarm64、x64とamd64の統一
