### ISSUE TITLE
音声ライブラリを管理する機能をサポートする

### ISSUE THREAD

**Issue by y-chan** [VOICEVOX/voicevox_project#21]
## 経緯・目的
- VOICEVOX 0.14.0 で #2 にて提案されていた構想がついにデプロイされ、VOICEVOX系エンジンのほぼすべての機能がVOICEVOXエディタ上で利用可能になりました。
- しかし、VOICEVOX系ソフトがそれぞれ個別に実装を行っていたキャラクターインストール機能(COEIROINK)や、音声ライブラリインストール機能(SHAREVOX)は各エディタから利用するしかなく、完全な統合は出来ていません。
- これを解決するために、VOICEVOXが音声ライブラリ管理機能を主導して開発し、各エディタに搭載されていた機能群を統合したいです。
  - 現状VOICEVOXがこの機能を利用する予定はないですが、Coreに後からライブラリをさせるようになったり、#3 を通して利用したりするかもしれないので、VOICEVOXとして進めていくことはメリットになると思います。
- ここで管理とは、具体的に4つの機能を指します。
  - ダウンロード
  - インポート
  - インストール
  - アンインストール

## 目標
- [ ] ネットワーク経由で音声ライブラリをダウンロード・インストール・アンインストールする機能を搭載する
  - [ ] API仕様(エンジンサイド)を確定させる
    - [ ] 必要なAPI設計について考える voicevox/voicevox_engine#536
    - [x] ダウンロード可能な音声ライブラリの一覧API voicevox/voicevox_engine#437
    - [ ] インストール済み音声ライブラリの一覧API voicevox/voicevox_engine#616
    - [ ] 音声ライブラリのインストールAPI voicevox/voicevox_engine#616
    - [ ] 音声ライブラリのアンインストールAPI
    - [ ] `supported_features`に音声ライブラリ管理機能について追加する voicevox/voicevox_engine#616
  - [ ] エディタのUIを作る
    - [ ] エディタのUIを考える
      - 複数エンジンの音声ライブラリ管理機能をいかに扱う(どう表示する)か？
      - 音声ライブラリのインストール前に、利用規約の同意を前提とするか？
      - 音声ライブラリのインストールは直列にするか、並列にするか？
        - 要は、インストールボタンを押したら「インストール中・・・」とブロックして他の作業が出来なくする(直列)か、「音声ライブラリのインストールが開始されました」とかを出して、インストール処理をキューに入れていって、それを順に処理していく感じ(並列)にするか
        - 音声ライブラリの反映にはエンジンの再起動が必要になるだろうけど、並列の場合その処理をどこで挟む(もしくは再起動をいつ促す)か？
        - 現実的なのは直列(並列はエラーハンドリングとかどうするの？になるので)
    - [ ] 実装する
      - VOICEVOX/voicevox#1063
      - ちょっと規模が大きくなりそうなので、一気に実装ではなく粒度を考えて分けて実装した方がよいかも？
  - [ ] インポート機能のための音声ライブラリファイル(`vvlib`)の設計を決める
    - [ ] `library_manifest.json`の仕様策定
      - `vvpp`のように、`engine_manifest.json`みたいなものが欲しい(インストール先のエンジンブランドの指定や、ライブラリのバージョン値などを埋め込んでおくため)
      - これに乗せる情報の仕様を決めておきたい
      - 例えば、どこにどの情報があるかなどをここに書き込んでしまうのもいいかもしれない。
    - [ ] (Optional?)ディレクトリ構造を決める
      - `library_manifest.json`のところに書いた通り、構造はすべて製作者のお任せにして、`library_manifest.json`に必要なファイルの情報をすべて書き込んでもらうのもいいかも
      - そもそもディレクトリ構造を決める必要はなくて(`library_manifest.json`が必ず存在することぐらいにしておいて)、各エンジンに処理をお任せしてしまう方針でもいいかも
- [ ] 音声ライブラリをインポートする機能を搭載する
  - MYCOEIROINKなどのユーザー製音声ライブラリを刺せるようにしたり、公式が配布しているライブラリを音声ライブラリ管理ダイアログからではなくブラウザなどでダウンロードしてきてインポートする役割として使う
  - [ ] API仕様を確定させる
    - 音声ライブラリのインポート自体はインストールAPIを使えば可能であるので、インストール機能の実装が前提 
    - [ ] 音声ライブラリの検証API(インストールしようとしている音声ライブラリは正しい形式であるかなどの検証処理)
  - [ ] エディタUIを作る
    - [ ] エディタUIを考える
      - 恐らく、音声ライブラリインストール機能と同じダイアログに統合されることとなる。
      - 音声ライブラリのインポート機能をどうするか？
        - ダウンロード可能なライブラリについては、あらかじめAPIから立ち絵・アイコンやボイスサンプル、利用規約などを取得出来るが、インポートする機能についてはそれが出来ない。
        - ファイルをエンジンに投げ、話者情報を取得するようにする？ 
        - 検証用APIにその役割を担わせる？
      - できる限り、ネットワーク経由の方で使うものと共通化した実装にした方が良さそう

##

**Comment by Hiroshiba** [comment]
issue作成ありがとうございます！！
頑張っていきたいですね！！

インポートとインストールは意味合いが似てるので混乱しそうですね！
たぶんインストールが「エンジンが返すダウンロードリストに載っている音声ライブラリを突っ込むこと」、インポートが「載っていないものを突っ込むこと」なのかなと思いました。
であればこの差分を仮の名称にしてしまうのが良いのかなと思いました！

「ユーザーモデルのサポート」とか･･･？

あと今のところ @sevenc-nanashi さんがPRを出してくださっていますが、そこにコメントをして機能を追加していくよりも、ちょっとずつ機能を区切ってPR・マージを高速に行うのが良いのかなと思いました！
そのPRはどこまで実装すべきかを意識して進めていきたいですね！

**Comment by y-chan** [comment]
> インポートとインストールは意味合いが似てるので混乱しそう

確かに、ちょっと意味合いが似ているかもですね...
ユーザーモデルのサポートとも限らないので、「リストからインストール」と「ファイルからインストール」とかどうかなとか思いました。

今の状況であれば、特定の人にタスクが偏ってしまいそうなので、これを分散させたいのは同意です。
目標をもう少しタスクレベルまで落とし込みたいなと思いました...!

**Comment by y-chan** [comment]
> 最初からvvlibを実装する

良いと思います！
インストールAPI自体がvvlibを展開するだけの機構になっていれば、流れがある程度共通化・統合できるので、分かりやすくなる上、管理のしやすさも上がると思いました...!

後でちょっとフローを図に起こしてみたいと思います:eyes:

**Comment by Hiroshiba** [comment]
良いと思います！　段取りなどおまかせします･･･！（判断困ったらいつでも頼っていただければ！）

**Comment by Hiroshiba** [comment]
こちらそろそろ動かしていけるかも？
ガシガシ設計プロトタイプ＆切り分けって感じでしょうか

**Comment by y-chan** [comment]
すみません...!
最近忙しくて返答が遅くなりました...

とりあえずは設計かなと思っています！
フロー図を用意したいのでもう少しだけ時間がかかりそうです...!

**Comment by y-chan** [comment]
前回の返信からまた時間が空いてしまいました、申し訳ないです....
フローは以下のような感じで行こうかなと思います。(mermaidをうまく使いこなせてなくて、きれいではないですが...)
```mermaid
flowchart TB;
    subgraph ネットワーク;
    server;
    end;
    subgraph ディスク;
    library_folder[ライブラリフォルダ];
    end;
    subgraph エディタ;
    file_select[エディタ上でのvvlibファイル選択];
    download[エディタ上でのvvlibダウンロード];
    library_select[エディタ上でのインストール済みライブラリ選択];
    end;
    subgraph エンジン;
    dl(downloadable_libraries);
    il(install_library);
    il2(installed_libraries);
    uil(uninstall_library);
    end;
    dl-->download;
    file_select-->il;
    download-->il;
    il2-->library_select;
    library_select-->uil;
    server-->dl;
    server-->download;
    il-->library_folder;
    library_folder-->il2;
    uil-->library_folder;
```
- まだアンインストールAPIができていないので、それの作成が必要になりそうです。ただ、必須級かと言われるとそうでもない気がするので、オプショナルでも良いかもしれません
  - アンインストールできない(プリインストールとかの)ライブラリを設定する必要があるかも...?`installed_libraries`に、アンインストールできるかの情報を含めたいかなと思いました。
- データのやり取り単位が`vvlib`になりそうなので、`vvlib`の仕様を決めたいです。
  - 各エンジンごとに、内包したいデータが異なるはずなので、ライブラリに関する最低限の情報を`library_manifest.json`に内包する方式にし、中のデータ処理は各エンジンにおまかせする方式で、十分に自由度を設定するのがいいかなと思いました。最低限欲しい情報は以下だと考えています。他に何か案があれば...!
    - `name`: 音声ライブラリの名前
    - `version`: 音声ライブラリのバージョン
    - `uuid`: 音声ライブラリのUUID
- ファイルからインストールする場合も、サンプル音声の試聴や、ライブラリインストール前の規約の確認フェーズがないと困るかなとちょっと思っているので、`vvlib`の中身のうち、それらのデータを返す処理が必要そうかなと思いました。ただし、その場合`vvlib`をエンジンに対して2回(データ抽出とインストール)投げることになるので、それを避けるいい方法を考えたいかも...?

ついでに、インストール時のユーザーフローも作成してみました。
```mermaid
flowchart TD;
    start[ライブラリ管理画面を開く];
    select_file[vvlibファイルを選ぶ];
    select_from_list[ダウンロード可能なライブラリを選ぶ];
    details_library(ライブラリ内の立ち絵や音声サンプル提示);
    view_tos(ライブラリ利用規約提示);
    install[インストール];
    start-->select_file;
    start-->select_from_list;
    select_file-->details_library;
    select_from_list-->details_library;
    details_library -->|次へ|view_tos;
    view_tos-->install;
```
- 音声サンプルや立ち絵についてはどちらでも良いかもしれませんが、ライブラリ内に入っているものを知るための手段としてほしいかなと思います(ライブラリ名だけではわからないこともあると思うので)
- ライブラリ利用規約の提示と同意は必要と思いましたが、いかがでしょうか？(特にユーザーモデルなどの場合は、トラブル防止のために「利用規約に同意してインストール」するボタンがあったほうが色々安心かなと思ったのですが、ユーザーが踏むステップの数は増えるので、UXは下がってしまうかも。)

**Comment by y-chan** [comment]
いろいろ決めるべきことが決まってないことに今気づきました...遅くなってすみません...

あまりにも分かりづらい全体図ができたのでとりあえず隠しておきます...
<summary>全体図</summary>
<details>

```mermaid
flowchart TB;
    subgraph ネットワーク;
    server;
    end;
    subgraph ディスク;
    library_folder[ライブラリフォルダ];
    end;
    subgraph エディタ;
    file_select[エディタ上でのvvlibファイルの選択];
    download_select[エディタ上でのダウンロードするvvlibの選択];
    confirm_download[エディタ上でのサンプルボイスや立ち絵と利用規約の確認];
    confirm_install[エディタ上でのサンプルボイスや立ち絵と利用規約の確認];
    library_select[エディタ上でのインストール済みライブラリ選択];
    download[エディタ上でのvvlibダウンロード];
    end;
    subgraph エンジン;
    dl(downloadable_libraries);
    il(install_library);
    il2(installed_libraries);
    uil(uninstall_library);
    vl(validate_library);
    end;
    dl-->download_select;
    il2-->library_select;
    library_select-->uil;
    server-->dl;
    il-->library_folder;
    library_folder-->il2;
    uil-->library_folder;
    file_select-->vl;
    vl-->confirm_install;
    download_select-->confirm_download;
    vl-->il;
    dl-->confirm_download;
    confirm_download-->download;
    download-->vl;
    download-->il;
    confirm_install-->il;
    server-->download;
    file_select-->confirm_install;
    il2-->|downloadable_librariesと照らし合わせてアップデート可能か確認|download_select;
```
</details>

> アプデフロー

エディタ上でインストール済みのものとバージョンと比較してインストール可能か判断する方式が良いかなと思いました。

```mermaid
flowchart TB;
    subgraph ネットワーク;
    server;
    end;
    subgraph エディタ;
    download_select[エディタ上でのダウンロードするvvlibの選択];
    confirm_download[エディタ上でのサンプルボイスや立ち絵と利用規約の確認];
    download[エディタ上でのvvlibダウンロード];
    end
    subgraph エンジン;
    dl(downloadable_libraries);
    il(install_library);
    il2(installed_libraries);
    vl(validate_library);
    end;
    subgraph ディスク;
    library_folder[ライブラリフォルダ];
    end;
    dl-->download_select;
    server-->dl;
    il-->library_folder;
    library_folder-->il2;
    download_select-->confirm_download;
    vl-->il;
    dl-->confirm_download;
    confirm_download-->download;
    download-->vl;
    download-->il;
    server-->download;
    il2-->|downloadable_librariesと照らし合わせてアップデート可能か確認|download_select;
```

> `brand_name`
> `manifest_version`

良さそうです！
今の所こんな感じでしょうか。

- `name`: 音声ライブラリの名前
- `version`: 音声ライブラリのバージョン
- `uuid`: 音声ライブラリのUUID
- `brand_name`: エンジンブランド (VOICEVOXなど)
- `engine_name`: エンジンの名前 (VOICEVOX Engineなど)
- `engine_uuid`: エンジンのUUID
- `manifest_version`: マニフェストバージョン

> vvlibからインストールするとなると、エンジンが持っている話者情報は全部必要かも
> データ抽出用のAPI用意すれば

vvlibファイル周りが若干ネックなのは変わりないのですが、`validate_library` API(仮名)をエンジン側に生やし、そこを通すと話者関連情報が得られるようにすれば良いかなと思いました。ここまでは今までの提案どおりなのですが、新たに`validate_library`を通さないとライブラリがインストール出来ないようにするのはどうかなと思いました。これは、`validate_library`の時点でエンジン側で音声ライブラリをキャッシュしておき、`install_library`時はファイルを渡すわけではなく、`library_uuid`などを使って`validate_library`時にキャッシュした情報からインストールするようにすれば、データの流れがある程度まとまって、処理の回数も減らせるのはないかなと思いました(全体図には少し反映しています)。
代わりに、インストールキャンセル時のために`destroy_library` API(仮名)とかもはやしてあげる必要があるのが若干ネックかもです。

validate以外のことをするという点で、名前は変えたほうがいいとは思いますが、いい名前が思い浮かばず...

**Comment by Hiroshiba** [comment]
@y-chan 

> 全体図

まとめてくださったの助かります、ありがとうございます！！
`エディタ上でのサンプルボイスや立ち絵と利用規約の確認`が２回あるの、ちょっと不自然だけど仕方ない感じですねぇ。

ここはエディタも絡むので @sevenc-nanashi さんの意見も聞いてみたいかもです。

> vvlibファイル周りが若干ネックなのは変わりないのですが、validate_library API(仮名)をエンジン側に生やし、そこを通すと話者関連情報が（略）

validateでデータが降ってくるというのはかなり挙動として謎ですが、ありかもと思いました。
キャッシュに関してですがそもそもzipなどからデータを取得するのは高速なので、ファイルパス指定であればキャッシュ不要にできそうに思いました。web APIとして変なのですが、まあ需要を考えるとこれでも良いかなという気持ちです･･･。
あるいは「仮登録（元validate）」で何かしらのIDを返し、その後ID指定して「インストール」･･･？

あとvvlibに話者関連情報を持たせない場合、エンジン側が知らないvvlibは追加できない、という感じになっちゃますね。VOICEVOXみたく全モデル把握してる場合は良いけど、ユーザーモデルの場合は不都合かも。（VOICEVOXの場合もNemoみたいなのは別途インストール可能にしたいかも）
大変な作業なので、優先度どうすべきなのか僕の中でまとまってないです。。

> brand_nameとか

持たせたい値、良さそうに思いました！
あと、エンジンのengine_manifest.json側に、対応しているライブラリのmanifest_versionをもたせたほうが良いかもとか思いました（supported_library_manifest_versionとか？）

**Comment by y-chan** [comment]
> `エディタ上でのサンプルボイスや立ち絵と利用規約の確認`が２回ある

これは、グラフ上で`エディタ上でのvvlibファイルの選択`からのものと`エディタ上でのダウンロードするvvlibの選択`からのもので、データフローが違うために分けているのと、グラフ上の同じノードを使うと処理が分かりにくくなるから分けただけで、多分実際には同じ処理を使うことになり、それぞれの工程で1回だけになると思います...!

> ファイルパス指定であればキャッシュ不要にできそう
> web APIとして変

私も、Web APIとしては変かなと思ったので、キャッシュ方式を考えていました。
ファイルパス方式だと、ディレクトリトラバーサルなどの、パス関連の問題が起きないかが少し気になるところですが、PCの外にAPIを公開しなければ問題にならないはずなので、一旦その方式でもいいかなと思いました。

> vvlibに話者関連情報を持たせない場合、エンジン側が知らないvvlibは追加できない、という感じになっちゃう

うーん、これは特に問題ないのではと思っています。
今のところ、COEIROINKのユーザーモデル機能では、zipファイルにモデルや`metas.json`と合わせて、話者関連情報なども含めて配布する形になっているので、話者関連情報をセットで配布することをを必須にするのは特に大きく問題となる気はしない気がしています(エンジンには、モデルの配置と話者関連情報の両方を配置してもらうように設計してもらえばいいと思っているのですが、それ以外に私が把握できていない問題がありそうですかね...?)。

> エンジンのengine_manifest.json側に、対応しているライブラリのmanifest_versionをもたせたほうが良い

これは確かにそうですね！エンジンが未対応のライブラリはインストールできないようにしないと、未対応の仕様に対応できずに変な動作が起きる可能性があると思うので、追加する必要はありそうだと思いました！

**Comment by y-chan** [comment]
> 実際バイナリ投げるのを作ってみて、遅そうだったりキャッシュ方式が作れなかったりしたら再考するとか･･･？

まあPoCを作ってみてどういうふうになるか見てみるのはわりとありだと思います！
バイナリを投げる方式は一度SHAREVOXで作ったことがあって、動きそうではあったので、キャッシュ方式の検証をちょっとやってみようかなと。

> OSS上のvvlibはスタイル番号やアイコンなどは含まず、各々のエンジンの独自仕様としてアイコンなどを追加してもらう、という理解で合っていますか･･･？ 👀

うーん、たしかにちょっと認識の齟齬がありそうです。
まず前提に、私自身はvvlibの仕様として話者関連情報は必ず含めなければならない仕様になっているべきではあると思っています。
ただ、それを`library_manifest.json`として同梱するかはちょっと検討した方がいいという意見でした。
多分、https://github.com/VOICEVOX/voicevox_project/issues/21#issuecomment-1485103760 の意見を見たときに、「話者関連情報も`library_manifest.json`として導入した方がいい」という意見として取ってしまったのが原因です...

なので、vvlib内に`speaker_info`フォルダを作り、そこにエンジンと同構造の話者関連情報を必ず導入するようにするといった仕様を決めちゃっていいかなと思います。
それであれば決まったフォルダを探索すれば話者関連情報を得られるので、以前例に上げた`validate`APIにvvlibを投げて話者関連情報を得ると言ったことをしなくとも、エディタ側でも処理可能になると思います。
簡易的なバリデーション(話者関連情報の取得と、`library_manifest.json`の検証)をエディタ側で行い、インストール時にエンジン側でしっかりとしてバリデーションを行えばフローも簡単化されていいかなと思いました。

あと、思ったのですが`library_manifest.json`じゃなくて`vvlib_manifes.json`のほうがいいのかもしれない...?(`engine_manifest.json`になぞらえるなら`library_manifes.json`だと思いますが、VOICEVOXにおいて`library`は動的ライブラリ: `core`の用語ではあると思うので)

**Comment by Hiroshiba** [comment]
あ、なるほどです！

`library_manifest.json`に全部書くのはたしかに大変かもです。
まあファイル構造だけ定義した場合、vvlibを読む側はOS違いに対応したり、いろんな音声ファイル・画像ファイルの拡張子に対応したり、将来互換性確認のためにファイル存在を調べたりしないといけなくなるので、jsonにしといたほうが全体で見ると楽かも･･･？
うーん！　でもファイル構造定める方針で良い気がしました！　将来ファイル構造変えねばってなったときに再検討しますか。

エディタ側であるvvlibから情報得るの、良い気がしました！
エディタ側の検証は、表示に必要な情報があるかのチェックくらいにしとくと楽そう。

> library_manifest.jsonじゃなくてvvlib_manifest.json

どちらでも良いかなと思いました！　どちらかというとvvlib_manifestが良さそうかなと。

**Comment by y-chan** [comment]
> エンジン側と共通化できるのは大きいし、ファイル構造定める方針で良い気がしました！
将来ファイル構造変えねばってなったときに再検討しますか。

今までファイル構造が変わったことは、スタイルごとに立ち絵が変更できる点ぐらいだったので、あまり神経質にならなくてもいいかなと思っています...!

> 表示に必要な情報があるかのチェックくらいにしとくと楽そう

そうですね、存在確認と、ファイル形式が問題ないかを検証するだけで、エディタ側で情報の表示が出来ると思うので、これでいいかなと思いました！

> どちらかというとvvlib_manifestが良さそうかなと。

`vvlib_manifest`で行こうと思います....!

**Comment by y-chan** [comment]
全体像がある程度まとまったと思うので、検証APIをなくした全体図を再掲しておきます。

```mermaid
flowchart TB;
    subgraph ネットワーク;
    server;
    end;
    subgraph ディスク;
    library_folder[ライブラリフォルダ];
    end;
    subgraph エディタ;
    file_select[エディタ上でのvvlibファイルの選択];
    extract_data[vvlibファイルの検証];
    download_select[エディタ上でのダウンロードするvvlibの選択];
    confirm_install[エディタ上でのサンプルボイスや立ち絵と利用規約の確認];
    library_select[エディタ上でのインストール済みライブラリ選択];
    download[エディタ上でのvvlibダウンロード];
    end;
    subgraph エンジン;
    dl(downloadable_libraries);
    il(install_library);
    il2(installed_libraries);
    uil(uninstall_library);
    end;
    dl-->download_select;
    il2-->library_select;
    library_select-->uil;
    server-->dl;
    il-->library_folder;
    library_folder-->il2;
    uil-->library_folder;
    download_select-->confirm_install;
    confirm_install-->|ダウンロードしてインストールの場合|download;
    download-->il;
    confirm_install-->|ファイルからインストールの場合|il;
    server-->download;
    file_select-->extract_data;
    extract_data-->confirm_install;
    il2-->|downloadable_librariesと照らし合わせてアップデート可能か確認|download_select;
```

この方向で不足しているAPIから実装していこうと思います...!
また、`vvlib`の最低限仕様は以下のようにしたいと思います
```
xxx.vvlib  # root
├─ vvlib_manifest.json
│       - name: 音声ライブラリの名前
│       - version: 音声ライブラリのバージョン
│       - uuid: 音声ライブラリのUUID
│       - brand_name: エンジンブランド (VOICEVOXなど)
│       - engine_name: エンジンの名前 (VOICEVOX Engineなど)
│       - engine_uuid: エンジンのUUID
│       - manifest_version: マニフェストバージョン
└─ speaker_info
     ├─ <uuid>
     │   ├─ icons
     │   │   └─ <x>.png
     │   ├─ portraits  # Optional
     │   │   └─ <x>.png
     │   ├─ voice_samples
     │   │   ├─ <x>_001.wav
     │   │   ├─ <x>_002.wav
     │   │   └─ <x>_003.wav
     │   ├─ metas.json
     │   ├─ policy.md
     │   └─ portrait.png
     └─ ...

```

**Comment by Hiroshiba** [comment]
良いと思います！！

音声ライブラリのアプデの議論ってしてましたっけ。installと全く同じ経路にして、uuidが既存だったら上書きが良いのかなと思いました！

**Comment by y-chan** [comment]
> 音声ライブラリのアプデの議論ってしてましたっけ。installと全く同じ経路にして、uuidが既存だったら上書きが良いのかなと思いました！

これで良いと思います！

**Comment by Hiroshiba** [comment]
メモです。
release-0.15で、エディタからのvvlib機能への対応情報表示をフィルタリングするようにしました。（まだ必ず非対応なため）
vvlib機能が正式サポートされたら忘れずに解除できればと！

**Comment by Hiroshiba** [comment]
@y-chan 
0.15のときにengine_manifestの`supported_vvlib_manifest_version`を消した（nullにした）のですが、これは引き続き消したままにしようと思います。
というのもまだ仕様が固まってなくて、どのバージョンが一番最初のバージョンになるかわからないので･･･。

`manage_library`の方はtrueにするので開発には支障がないと思っていますが、最終的にリリースする時に入れ忘れないよう注意が必要かもです。
（まあ入れ忘れたとしても、一番最初に破壊的変更があった時に書けば問題ないと思います）

**Comment by qryxip** [comment]
↑ ユーザーから見える「音声ライブラリ」をどう形作るかにおいて、声のバージョンという概念が関わりうると思ったので一応リンクを貼った次第です。vvlib自体のバージョニング(あるいはID)をどう定めていくかに関わってくるかなと思ってます。

ちなみにVVMの方では、「声が明確に変化するかもしくは削除されるような変更」のときにUUIDを更新するという方向になっています。
[feat: `VoiceModelId`が指すIDの意味を書く by qryxip · Pull Request #1143 · VOICEVOX/voicevox_core](https://github.com/VOICEVOX/voicevox_core/pull/1143)
